source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JRSplitVC_Example', :exclusive => true do
  pod "JRSplitVC", :path => "../"
end

target 'JRSplitVC_Tests', :exclusive => true do
  pod "JRSplitVC", :path => "../"

  pod 'Kiwi'
end
